### ISSUE TITLE
Attempt to decode JSON with unexpected mimetype: text/plain

### ISSUE THREAD

**Issue by ShonkyCH** [Bre77/myair#1]
Hey thanks for having a go at this. I tried and have some basic JSON parsing etc but don't know python well enough. Anyway I tried on a real system and got this

I can provide the actual JSON (after removing personal details) if you need.

```
2020-08-10 14:58:43 DEBUG (MainThread) [custom_components.myair] Setting up MyAir
2020-08-10 14:58:46 ERROR (MainThread) [custom_components.myair] Error fetching MyAir data: Error getting MyAir data: 0, message='Attempt to decode JSON with unexpected mimetype: text/plain', url='http://192.168.99.24:2025/getSystemData
2020-08-10 14:58:46 DEBUG (MainThread) [custom_components.myair] Finished fetching MyAir data in 3.244 seconds
2020-08-10 14:58:46 ERROR (MainThread) [homeassistant.setup] Error during setup of component myair
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 193, in _async_setup_component
    result = await asyncio.wait_for(task, SLOW_SETUP_MAX_WAIT)
  File "/usr/local/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/config/custom_components/myair/__init__.py", line 84, in async_setup
    "identifiers": {(DOMAIN, coordinator.data['system']['mid'])},
TypeError: 'NoneType' object is not subscriptable
```

**Comment by Bre77** [comment]
I suspect this is because the "mid" value isn't populated in your system. If you could send me the output of http://192.168.99.24:2025/getSystemData from your web browser that would help.

**Comment by ShonkyCH** [comment]
mid is 61057. The error seems to indicate it doesn't like the fact the webserver sends the Content-Type as text/plain though instead of application/json. Postman has a similar problem interpreting it and you have to specifically tell it to format as JSON.

```
{
    "aircons": {
        "ac1": {
            "info": {
                "aaAutoFanModeEnabled": true,
                "activationCodeStatus": "noCode",
                "airconErrorCode": "",
                "cbFWRevMajor": 8,
                "cbFWRevMinor": 20,
                "cbType": 1,
                "climateControlModeEnabled": false,
                "climateControlModeIsRunning": false,
                "constant1": 6,
                "constant2": 0,
                "constant3": 0,
                "countDownToOff": 0,
                "countDownToOn": 0,
                "fan": "auto",
                "filterCleanStatus": 0,
                "freshAirStatus": "none",
                "mode": "heat",
                "myAutoModeCurrentSetMode": "heat",
                "myAutoModeEnabled": false,
                "myAutoModeIsRunning": false,
                "myZone": 6,
                "name": "AC",
                "noOfConstants": 1,
                "noOfZones": 7,
                "quietNightModeEnabled": false,
                "quietNightModeIsRunning": false,
                "rfSysID": 12,
                "setTemp": 16.0,
                "state": "off",
                "uid": "61057",
                "unitType": 18
            },
            "zones": {
                "z01": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 21.2,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 1",
                    "number": 1,
                    "rssi": 47,
                    "setTemp": 24.0,
                    "state": "close",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                },
                "z02": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 21.3,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 2",
                    "number": 2,
                    "rssi": 54,
                    "setTemp": 24.0,
                    "state": "close",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                },
                "z03": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 21.1,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 3",
                    "number": 3,
                    "rssi": 45,
                    "setTemp": 24.0,
                    "state": "close",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                },
                "z04": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 20.8,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 4",
                    "number": 4,
                    "rssi": 38,
                    "setTemp": 24.0,
                    "state": "close",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                },
                "z05": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 21.0,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 5",
                    "number": 5,
                    "rssi": 49,
                    "setTemp": 25.0,
                    "state": "close",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                },
                "z06": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 20.2,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 6",
                    "number": 6,
                    "rssi": 51,
                    "setTemp": 24.0,
                    "state": "open",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                },
                "z07": {
                    "error": 0,
                    "maxDamper": 100,
                    "measuredTemp": 20.1,
                    "minDamper": 0,
                    "motion": 0,
                    "motionConfig": 1,
                    "name": "Zone 7",
                    "number": 7,
                    "rssi": 52,
                    "setTemp": 25.0,
                    "state": "close",
                    "tempSensorClash": false,
                    "type": 1,
                    "value": 100
                }
            }
        }
    },
    "myAddOns": {
        "hueBridges": {},
        "hueBridgesOrder": []
    },
    "myLights": {
        "groups": {},
        "groupsOrder": [],
        "lights": {},
        "system": {
            "sunsetTime": "05:24 PM"
        }
    },
    "myMonitors": {
        "monitors": {
            "n10002": {
                "actions": {
                    "aircons": {
                        "ac1": {
                            "info": {
                                "fan": "auto",
                                "freshAirStatus": "none",
                                "mode": "heat",
                                "myZone": 6,
                                "name": "AC",
                                "setTemp": 16.0,
                                "state": "on",
                                "uid": "61057"
                            },
                            "zones": {
                                "z01": {
                                    "motionConfig": 1,
                                    "number": 1,
                                    "setTemp": 24.0,
                                    "state": "open",
                                    "tempSensorClash": false,
                                    "value": 65
                                },
                                "z02": {
                                    "motionConfig": 1,
                                    "number": 2,
                                    "setTemp": 24.0,
                                    "state": "open",
                                    "tempSensorClash": false,
                                    "value": 70
                                },
                                "z03": {
                                    "motionConfig": 1,
                                    "number": 3,
                                    "setTemp": 24.0,
                                    "state": "close",
                                    "tempSensorClash": false,
                                    "value": 40
                                },
                                "z04": {
                                    "motionConfig": 1,
                                    "number": 4,
                                    "setTemp": 24.0,
                                    "state": "open",
                                    "tempSensorClash": false,
                                    "value": 70
                                },
                                "z05": {
                                    "motionConfig": 1,
                                    "number": 5,
                                    "setTemp": 25.0,
                                    "state": "close",
                                    "tempSensorClash": false,
                                    "value": 100
                                },
                                "z06": {
                                    "motionConfig": 1,
                                    "number": 6,
                                    "setTemp": 24.0,
                                    "state": "open",
                                    "tempSensorClash": false,
                                    "value": 100
                                },
                                "z07": {
                                    "motionConfig": 1,
                                    "number": 7,
                                    "setTemp": 25.0,
                                    "state": "close",
                                    "tempSensorClash": false,
                                    "value": 100
                                }
                            }
                        }
                    },
                    "airconsEnabled": true,
                    "autoActionEnabled": true,
                    "autoActionSummary": "Auto action configuration:\n\nMyAir:\nAircon: on, mode: heat, fan speed: auto, 24°C\nopen zones:\nZone 1*",
                    "lights": {},
                    "lightsEnabled": false,
                    "notificationEnabled": true,
                    "notificationPhoneNumber": "",
                    "notificationPhoneNumberEnabled": false,
                    "things": {},
                    "thingsEnabled": false
                },
                "activeDays": 62,
                "endTime": 480,
                "events": {
                    "garageDoorEnabled": false,
                    "motionSensorEnabled": false,
                    "suburbTempBelowThresholdSelected": false,
                    "suburbTempEnabled": false,
                    "suburbTempThresholdValue": 28,
                    "weatherConditionForPvEnabled": false,
                    "zoneTempAirconId": "ac1",
                    "zoneTempBelowThresholdSelected": true,
                    "zoneTempEnabled": true,
                    "zoneTempThresholdValue": 18
                },
                "id": "n10002",
                "monitorEnabled": true,
                "monitorSummary": "This event is active between:\n6:00 AM and 8:00 AM\non these days:\nMonday, Tuesday, Wednesday, Thursday, Friday\n\nconditions:\n- any zone temp is below 18°C\n\ntasks:\n- send notification\n- auto action\n\n",
                "name": "Monitor 2",
                "startTime": 360
            },
            "n10001": {
                "actions": {
                    "autoActionEnabled": false,
                    "autoActionSummary": "",
                    "notificationEnabled": true
                },
                "activeDays": 127,
                "endTime": 0,
                "events": {
                    "suburbTempAboveValue": 30,
                    "suburbTempEnabled": true,
                    "suburbTempThresholdValue": 30
                },
                "id": "n10001",
                "monitorEnabled": true,
                "monitorSummary": "This event is active between:\n12:00 AM and 12:00 AM(next day)\non these days:\nMonday, Tuesday, Wednesday, Thursday, Friday, Saturday, Sunday\n\nconditions:\n- suburb temp is above 30°C\n\ntasks:\n- send notification\n\n",
                "name": "Monitor 1",
                "startTime": 0
            }
        },
        "monitorsOrder": [
            "n10001",
            "n10002"
        ]
    },
    "myScenes": {
        "scenes": {
            "s0": {
                "aircons": {
                    "ac1": {
                        "info": {
                            "fan": "auto",
                            "freshAirStatus": "none",
                            "mode": "cool",
                            "myZone": 6,
                            "name": "AC",
                            "setTemp": 16.0,
                            "state": "on",
                            "uid": "61057"
                        },
                        "zones": {
                            "z01": {
                                "motionConfig": 1,
                                "number": 1,
                                "setTemp": 28.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 5
                            },
                            "z02": {
                                "motionConfig": 1,
                                "number": 2,
                                "setTemp": 23.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z03": {
                                "motionConfig": 1,
                                "number": 3,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z04": {
                                "motionConfig": 1,
                                "number": 4,
                                "setTemp": 28.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 35
                            },
                            "z05": {
                                "motionConfig": 1,
                                "number": 5,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z06": {
                                "motionConfig": 1,
                                "number": 6,
                                "setTemp": 25.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z07": {
                                "motionConfig": 1,
                                "number": 7,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            }
                        }
                    }
                },
                "id": "s0",
                "name": "MyUndo",
                "summary": "Days this scene will run:\nnone\n\nMyAir:\nAircon: on, mode: cool, fan speed: auto, 25°C\nopen zones:\nZone 1*"
            },
            "s10001": {
                "activeDays": 62,
                "airconStopTime": 480,
                "airconStopTimeEnabled": true,
                "aircons": {
                    "ac1": {
                        "info": {
                            "fan": "auto",
                            "freshAirStatus": "none",
                            "mode": "heat",
                            "myZone": 6,
                            "name": "AC",
                            "setTemp": 16.0,
                            "state": "on",
                            "uid": "61057"
                        },
                        "zones": {
                            "z01": {
                                "motionConfig": 1,
                                "number": 1,
                                "setTemp": 23.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 5
                            },
                            "z02": {
                                "motionConfig": 1,
                                "number": 2,
                                "setTemp": 23.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 55
                            },
                            "z03": {
                                "motionConfig": 1,
                                "number": 3,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z04": {
                                "motionConfig": 1,
                                "number": 4,
                                "setTemp": 23.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z05": {
                                "motionConfig": 1,
                                "number": 5,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z06": {
                                "motionConfig": 1,
                                "number": 6,
                                "setTemp": 23.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z07": {
                                "motionConfig": 1,
                                "number": 7,
                                "setTemp": 24.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            }
                        }
                    }
                },
                "id": "s10001",
                "lights": {},
                "myTimeEnabled": false,
                "name": "Morning Heat",
                "startTime": 375,
                "summary": "Days this scene will run:\nMonday, Tuesday, Wednesday, Thursday, Friday\n\nMyAir:\nAircon: on, mode: heat, fan speed: auto, 23°C\nopen zones:\nZone 1*",
                "things": {},
                "timerEnabled": false
            },
            "s10002": {
                "activeDays": 62,
                "airconStopTime": 510,
                "airconStopTimeEnabled": true,
                "aircons": {
                    "ac1": {
                        "info": {
                            "fan": "auto",
                            "freshAirStatus": "none",
                            "mode": "cool",
                            "myZone": 6,
                            "name": "AC",
                            "setTemp": 16.0,
                            "state": "off",
                            "uid": "61057"
                        },
                        "zones": {
                            "z01": {
                                "motionConfig": 1,
                                "number": 1,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z02": {
                                "motionConfig": 1,
                                "number": 2,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z03": {
                                "motionConfig": 1,
                                "number": 3,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z04": {
                                "motionConfig": 1,
                                "number": 4,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z05": {
                                "motionConfig": 1,
                                "number": 5,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z06": {
                                "motionConfig": 1,
                                "number": 6,
                                "setTemp": 25.0,
                                "state": "open",
                                "tempSensorClash": false,
                                "value": 100
                            },
                            "z07": {
                                "motionConfig": 1,
                                "number": 7,
                                "setTemp": 25.0,
                                "state": "close",
                                "tempSensorClash": false,
                                "value": 100
                            }
                        }
                    }
                },
                "id": "s10002",
                "lights": {},
                "myTimeEnabled": false,
                "name": "AC off",
                "startTime": 495,
                "summary": "Days this scene will run:\nMonday, Tuesday, Wednesday, Thursday, Friday\n\nMyAir:\nAircon: off",
                "things": {},
                "timerEnabled": false
            }
        },
        "scenesOrder": [
            "s10001",
            "s10002"
        ]
    },
    "mySensors": {
        "sensors": {},
        "sensorsOrder": []
    },
    "myThings": {
        "groups": {},
        "groupsOrder": [],
        "system": {},
        "things": {}
    },
    "snapshots": {},
    "system": {
        "aaServiceRev": "14.88",
        "allTspErrorCodes": {},
        "country": "Australia",
        "dealerPhoneNumber": "deleted",
        "deviceIds": [
            "deleted",
            "deleted"
        ],
        "deviceIdsV2": {
            "deleted": "deleted",
            "deleted": "deleted"
        },
        "drawLightsTab": false,
        "drawThingsTab": false,
        "garageDoorReminderWaitTime": 2,
        "hasAircons": true,
        "hasLights": false,
        "hasSensors": false,
        "hasThings": false,
        "hasThingsBOG": false,
        "hasThingsLight": false,
        "latitude": -27.000000,
        "logoPIN": "1234",
        "longitude": 150.000000,
        "mid": "61057",
        "myAppRev": "15.810",
        "name": "deleted",
        "needsUpdate": false,
        "noOfAircons": 1,
        "noOfSnapshots": 0,
        "postCode": "1234",
        "rid": "deleted",
        "showMeasuredTemp": true,
        "sysType": "MyAir5",
        "tspErrorCode": "noError",
        "tspIp": "192.168.99.24",
        "tspModel": "PIC8KS6-TSP7",
        "versions": {}
    }
}
```

**Comment by ShonkyCH** [comment]
Seems to work:
```
            resp = await session.get(f"{uri_scheme}{host}:{port}/getSystemData")
            data = await resp.read()
            #assert resp.status == 200
            return json.loads(data)
```

**Comment by Bre77** [comment]
> Seems to work:
> ```
>             resp = await session.get(f"{uri_scheme}{host}:{port}/getSystemData")
>             data = await resp.read()
>             #assert resp.status == 200
>             return json.loads(data)
> ```

I'll change my logic to something similar. Thanks for identifying and reporting this.

**Comment by Bre77** [comment]
Fixed in master branch. Please remove your config from Configuration.yaml as the integration now uses Config Flow in the UI.

For refence I changed it to:
`data = await resp.json(content_type=None)`
